name: Auto Move Issue in Project Board

on:
  issues:
    types: [opened, assigned, closed]

jobs:
  move_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Move Issue to "To Do" when created
        if: github.event.action == 'opened'
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"content_id": "${{ github.event.issue.node_id }}", "project_id": 4 , "field_id": "status", "value": "To Do"}' \
               https://api.github.com/graphql

      - name: Move Issue to "In Progress" when assigned
        if: github.event.action == 'assigned'
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"content_id": "${{ github.event.issue.node_id }}", "project_id": 4, "field_id": "status", "value": "In Progress"}' \
               https://api.github.com/graphql

      - name: Move Issue to "Done" when closed
        if: github.event.action == 'closed'
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Content-Type: application/json" \
               -d '{"content_id": "${{ github.event.issue.node_id }}", "project_id": 4, "field_id": "status", "value": "Done"}' \
               https://api.github.com/graphql
