name: Auto Move Issue in Project Board

on:
  issues:
    types: [opened, assigned, closed]

jobs:
  move_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Move Issue to "To Do" when created
        if: github.event.action == 'opened'
        uses: octokit/request-action@v2.x
        with:
          route: POST /projects/columns/cards
          column_id: 12345678  # ID của cột "To Do"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Issue to "In Progress" when assigned
        if: github.event.action == 'assigned'
        uses: octokit/request-action@v2.x
        with:
          route: POST /projects/columns/cards
          column_id: Y3Vyc29yOnYyOpLOCrwoVKRUb2Rv  # ID của cột "In Progress"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Issue to "Done" when closed
        if: github.event.action == 'closed'
        uses: octokit/request-action@v2.x
        with:
          route: POST /projects/columns/cards
          column_id: 56781234  # ID của cột "Done"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
