name: Auto Move Issue in Project Board

on:
  issues:
    types: [opened, assigned, closed]

jobs:
  move_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Move Issue to "To Do" when created
        if: github.event.action == 'opened'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.inertia-preview+json" \
               https://api.github.com/projects/columns/12345678/cards \
               -d '{"content_id": "${{ github.event.issue.id }}", "content_type": "Issue"}'

      - name: Move Issue to "In Progress" when assigned
        if: github.event.action == 'assigned'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.inertia-preview+json" \
               https://api.github.com/projects/columns/87654321/cards \
               -d '{"content_id": "${{ github.event.issue.id }}", "content_type": "Issue"}'

      - name: Move Issue to "Done" when closed
        if: github.event.action == 'closed'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.inertia-preview+json" \
               https://api.github.com/projects/columns/56781234/cards \
               -d '{"content_id": "${{ github.event.issue.id }}", "content_type": "Issue"}'
